### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by pabloblopez** [Het-SCD/Het-SCD#1]
I have the following software: gcc 4.8.2, GNU Make 3.81, nvcc 5.5. Thanks.
![screenshot at 2018-03-06 12-37-35](https://user-images.githubusercontent.com/36965893/37030512-801e7500-213b-11e8-82e6-6ea7eeebb204.png)

**Comment by stijnh** [comment]
Thank you for your issue. Unfortunately, the ModernGPU library has had a major rewrite which means the newest version 2.0 is no longer compatible with Het-SCD. Please use [version 1.1](https://github.com/moderngpu/moderngpu/releases/tag/V1.1) instead. Download this version, extract in some directory and change `MGPU_PATH` in `config.mk` to point to this directory.

**Comment by pabloblopez** [comment]
Thank you.
![screenshot at 2018-03-06 16-20-36](https://user-images.githubusercontent.com/36965893/37040625-968c4a00-215a-11e8-989e-23b653b580f8.png)
After having installed moderngpu-branch_1.1 I have the following error:

![screenshot at 2018-03-06 16-25-48](https://user-images.githubusercontent.com/36965893/37040837-0b718024-215b-11e8-9f9b-7186be0efb18.png)

**Comment by stijnh** [comment]
It seems Het-SCD is currently unable to be compiled with neither ModernGPU v1.0 or v1.1. Het-SCD was created while ModernGPU was in active development, somewhere after v1.0 and just before v1.1, meaning it is currently incompatible with both versions.

 I've added a hotfix to support ModernGPU v1.1 inside a new branch. Please pull the latest commits, switch to branch `moderngpu-1.1` using `git checkout moderngpu-1.1` and check if this compiles for you. I was able to compile the project successfully on my machine using `nvcc 9.1` en `gcc 4.8`.

**Comment by pabloblopez** [comment]
Thanks, perfect, I've been able to compile it successfully.

**Comment by stijnh** [comment]
Great! I am very curious how you plan on using Het-SCD in your work. If you would like to tell me more or need any more assistance, don't hesitate to shoot me an e-mail (see my profile). I will close this issue for now.
